# Generated by Django 5.0.6 on 2024-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contact_initials_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.ManyToManyField(to='api.contact'),
        ),
        migrations.AddField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(to='api.subtask'),
        ),
    ]
