# Generated by Django 5.0.6 on 2024-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_todo_assigned_to_remove_todo_subtasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='api.contact'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(blank=True, to='api.subtask'),
        ),
    ]
