# Generated by Django 5.0.6 on 2024-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_assigned_to_alter_todo_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
